import { Lead, DashboardStats, GlobeOpportunity, OutreachTemplate } from './types'

export const DASHBOARD_STATS: DashboardStats = {
  totalLeads: 4872,
  hotLeads: 347,
  warmLeads: 1284,
  coldLeads: 3241,
  opportunities: 12450,
  pipelineValue: '$4.7M',
  conversionRate: 18.4,
  newThisWeek: 124,
  outreachSent: 892,
  responseRate: 31.2,
}

export const GLOBE_OPPORTUNITIES: GlobeOpportunity[] = [
  { lat: 40.7128, lng: -74.0060, city: 'New York', country: 'USA', count: 342, industries: ['Finance', 'Tech', 'Healthcare'], marketSize: '$2.1B', color: '#00D4FF' },
  { lat: 51.5074, lng: -0.1278, city: 'London', country: 'UK', count: 289, industries: ['Finance', 'Media', 'Retail'], marketSize: '$1.8B', color: '#00D4FF' },
  { lat: 35.6762, lng: 139.6503, city: 'Tokyo', country: 'Japan', count: 256, industries: ['Tech', 'Manufacturing', 'Finance'], marketSize: '$2.4B', color: '#6C63FF' },
  { lat: 48.8566, lng: 2.3522, city: 'Paris', country: 'France', count: 234, industries: ['Luxury', 'Fashion', 'Tech'], marketSize: '$980M', color: '#00D4FF' },
  { lat: 37.7749, lng: -122.4194, city: 'San Francisco', country: 'USA', count: 312, industries: ['Tech', 'Startup', 'AI'], marketSize: '$3.2B', color: '#FF6B6B' },
  { lat: 1.3521, lng: 103.8198, city: 'Singapore', country: 'Singapore', count: 187, industries: ['Finance', 'Logistics', 'Tech'], marketSize: '$850M', color: '#6C63FF' },
  { lat: 25.2048, lng: 55.2708, city: 'Dubai', country: 'UAE', count: 276, industries: ['Real Estate', 'Finance', 'Hospitality'], marketSize: '$1.5B', color: '#FF6B6B' },
  { lat: 19.0760, lng: 72.8777, city: 'Mumbai', country: 'India', count: 223, industries: ['Finance', 'IT', 'E-Commerce'], marketSize: '$760M', color: '#6C63FF' },
  { lat: 31.2304, lng: 121.4737, city: 'Shanghai', country: 'China', count: 298, industries: ['Manufacturing', 'Finance', 'E-Commerce'], marketSize: '$2.8B', color: '#00D4FF' },
  { lat: -33.8688, lng: 151.2093, city: 'Sydney', country: 'Australia', count: 198, industries: ['Finance', 'Healthcare', 'Retail'], marketSize: '$720M', color: '#6C63FF' },
  { lat: 52.5200, lng: 13.4050, city: 'Berlin', country: 'Germany', count: 167, industries: ['Tech', 'Startup', 'Manufacturing'], marketSize: '$890M', color: '#00D4FF' },
  { lat: -23.5505, lng: -46.6333, city: 'São Paulo', country: 'Brazil', count: 145, industries: ['Retail', 'Finance', 'Agriculture'], marketSize: '$540M', color: '#6C63FF' },
  { lat: 55.7558, lng: 37.6173, city: 'Moscow', country: 'Russia', count: 134, industries: ['Energy', 'Finance', 'Tech'], marketSize: '$430M', color: '#6C63FF' },
  { lat: 19.4326, lng: -99.1332, city: 'Mexico City', country: 'Mexico', count: 156, industries: ['Manufacturing', 'Finance', 'Retail'], marketSize: '$380M', color: '#6C63FF' },
  { lat: 30.0444, lng: 31.2357, city: 'Cairo', country: 'Egypt', count: 143, industries: ['Tourism', 'Finance', 'Retail'], marketSize: '$290M', color: '#6C63FF' },
]

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    company: 'NexaTech Solutions',
    website: 'nexatech.com',
    industry: 'Technology',
    sector: 'SaaS',
    location: 'Austin, TX',
    country: 'United States',
    countryCode: 'US',
    employees: '250-500',
    revenue: '$15M - $25M',
    founded: '2018',
    description: 'B2B SaaS platform for supply chain management serving mid-market manufacturers.',
    score: 94,
    scoreCategory: 'hot',
    websiteScore: 42,
    seoScore: 38,
    mobileScore: 51,
    performanceScore: 44,
    securityScore: 67,
    aiInsight: 'NexaTech is rapidly scaling with 3 recent enterprise deals but their digital infrastructure is lagging significantly. Their website conversion rate is estimated at 1.2% vs industry average of 3.8%. They are hiring 5 frontend engineers indicating they know they have a problem but lack the specialized talent. Fixels can provide immediate value through a complete digital overhaul — estimated $2.4M opportunity.',
    fundingStage: 'Series B',
    fundingAmount: '$18M',
    opportunities: {
      website: {
        score: 91,
        label: 'Critical',
        priority: 'high',
        impact: '$180K+ revenue uplift potential',
        insights: [
          'Website last redesigned in 2019 — significantly outdated',
          'Mobile bounce rate at 73% (industry avg: 42%)',
          'Page load time: 6.8s (should be <2s)',
          'No structured data or schema markup',
          'Missing conversion optimization elements',
        ],
      },
      mobile: {
        score: 87,
        label: 'High Priority',
        priority: 'high',
        impact: '35% customer retention improvement',
        insights: [
          'No native mobile app despite 68% mobile traffic',
          'Competitors TechFlow and SupplyAI both have apps',
          'Customer requests for mobile access in 23 support tickets',
          'Field operations team needs offline capability',
        ],
      },
      erp: {
        score: 72,
        label: 'Recommended',
        priority: 'medium',
        impact: '$420K annual efficiency savings',
        insights: [
          'Using 6 disconnected tools for operations',
          'Manual reconciliation taking 40+ hours/week',
          'Recent LinkedIn posts about operational challenges',
          'HR director posted about "broken processes"',
        ],
      },
      marketing: {
        score: 88,
        label: 'High Priority',
        priority: 'high',
        impact: '3x organic traffic growth potential',
        insights: [
          'Domain authority score: 22 (competitors: 45-60)',
          'Zero blog content in last 6 months',
          'Google Ads spend detected but no SEO investment',
          'Competitors outranking on 94% of target keywords',
        ],
      },
      outsourcing: {
        score: 78,
        label: 'Opportunity',
        priority: 'medium',
        impact: '40% development cost reduction',
        insights: [
          '5 open frontend developer roles for 3+ months',
          'Glassdoor reviews mention "slow product releases"',
          'CTO posted about engineering capacity challenges',
        ],
      },
    },
    contacts: [
      { name: 'Marcus Reed', role: 'CEO & Co-Founder', linkedin: 'linkedin.com/in/marcusreed', email: 'm.reed@nexatech.com' },
      { name: 'Sarah Chen', role: 'CTO', linkedin: 'linkedin.com/in/sarachen-cto', email: 's.chen@nexatech.com' },
      { name: 'David Park', role: 'VP Marketing', linkedin: 'linkedin.com/in/davidpark' },
    ],
    social: {
      linkedin: 'linkedin.com/company/nexatech-solutions',
      twitter: 'twitter.com/nexatech',
    },
    techStack: ['React', 'Node.js', 'AWS', 'Salesforce', 'HubSpot'],
    intentSignals: [
      { type: 'hiring', description: 'Posted 5 new engineering roles in last 30 days', date: '2026-05-28', strength: 'strong' },
      { type: 'funding', description: 'Closed $18M Series B — accelerating digital transformation', date: '2026-05-15', strength: 'strong' },
      { type: 'expansion', description: 'Opened new office in Chicago, expanding east coast presence', date: '2026-05-10', strength: 'medium' },
    ],
    lastActivity: '2 days ago',
    addedDate: '2026-05-30',
  },
  {
    id: 'lead-002',
    company: 'Harborview Hospitality',
    website: 'harborviewhotels.com',
    industry: 'Hospitality',
    sector: 'Hotels & Resorts',
    location: 'Miami, FL',
    country: 'United States',
    countryCode: 'US',
    employees: '500-1000',
    revenue: '$45M - $80M',
    founded: '2009',
    description: 'Luxury boutique hotel chain with 12 properties across the US Caribbean.',
    score: 88,
    scoreCategory: 'hot',
    websiteScore: 35,
    seoScore: 44,
    mobileScore: 38,
    performanceScore: 52,
    securityScore: 58,
    aiInsight: 'Harborview is losing an estimated $3.2M annually to OTA commissions (Expedia, Booking.com) because their direct booking platform is outdated and clunky. A modern website with a superior booking experience could shift 20-30% of bookings to direct, saving massive commission fees while improving guest satisfaction.',
    opportunities: {
      website: {
        score: 95,
        label: 'Critical',
        priority: 'high',
        impact: '$3.2M annual direct booking potential',
        insights: [
          'Current site converts at 0.8% vs luxury hotel avg of 3.2%',
          'Booking engine is a third-party widget with poor UX',
          'No virtual room tours or immersive gallery',
          'Competitor Four Seasons direct booking is 4x smoother',
          'Mobile checkout abandonment at 89%',
        ],
      },
      mobile: {
        score: 83,
        label: 'High Priority',
        priority: 'high',
        impact: '45% repeat booking increase',
        insights: [
          'No guest app for check-in, room service, concierge',
          'Luxury guests expect seamless digital experiences',
          'Marriott Bonvoy app increased repeat bookings by 52%',
        ],
      },
      erp: { score: 61, label: 'Moderate', priority: 'medium', impact: '$280K efficiency savings', insights: ['Property management systems not integrated', 'Manual inventory tracking across 12 properties'] },
      marketing: {
        score: 74,
        label: 'Opportunity',
        priority: 'medium',
        impact: '$850K additional revenue from digital marketing',
        insights: ['TripAdvisor presence weak vs competitors', 'Instagram engagement only 0.8% (avg: 3.2% for luxury)', 'No remarketing campaigns running'],
      },
      outsourcing: { score: 45, label: 'Low Priority', priority: 'low', impact: 'Cost savings on IT support', insights: ['Has in-house IT team of 4', 'Could benefit from specialized web development talent'] },
    },
    contacts: [
      { name: 'Victoria Harmon', role: 'CEO', linkedin: 'linkedin.com/in/victoriaharmon' },
      { name: 'James Liu', role: 'Chief Digital Officer', email: 'j.liu@harborviewhotels.com' },
    ],
    social: {
      linkedin: 'linkedin.com/company/harborview-hospitality',
      instagram: 'instagram.com/harborviewhotels',
      facebook: 'facebook.com/harborviewhotels',
    },
    techStack: ['WordPress', 'Stripe', 'Oracle PMS', 'Google Analytics'],
    intentSignals: [
      { type: 'website-update', description: 'CMO mentioned website redesign in conference talk', date: '2026-05-20', strength: 'strong' },
      { type: 'expansion', description: 'Signed lease for 2 new properties in Q3', date: '2026-05-12', strength: 'medium' },
    ],
    lastActivity: '4 days ago',
    addedDate: '2026-05-28',
  },
  {
    id: 'lead-003',
    company: 'GreenLeaf Organics',
    website: 'greenleaforganics.co',
    industry: 'E-Commerce',
    sector: 'Health & Wellness',
    location: 'Portland, OR',
    country: 'United States',
    countryCode: 'US',
    employees: '50-100',
    revenue: '$8M - $15M',
    founded: '2020',
    description: 'DTC organic food and supplements brand with strong social following but limited digital infrastructure.',
    score: 82,
    scoreCategory: 'hot',
    websiteScore: 54,
    seoScore: 61,
    mobileScore: 47,
    performanceScore: 48,
    securityScore: 72,
    aiInsight: 'GreenLeaf has explosive social media growth (280K Instagram followers) but their Shopify store is a basic template that cannot scale. Cart abandonment is at 78% — nearly double the 45% industry average. Their subscription revenue model has huge untapped potential that requires custom e-commerce development.',
    fundingStage: 'Seed',
    fundingAmount: '$3.2M',
    opportunities: {
      website: { score: 86, label: 'High Priority', priority: 'high', impact: '$420K additional annual revenue', insights: ['78% cart abandonment vs 45% industry avg', 'Basic Shopify template — no brand differentiation', 'No subscription/loyalty program infrastructure', 'Products out of stock with no waitlist system'] },
      mobile: { score: 79, label: 'High Priority', priority: 'high', impact: '55% repeat purchase increase', insights: ['67% of traffic is mobile but experience is poor', 'No push notifications for promotions', 'Social-to-purchase funnel is broken on mobile'] },
      erp: { score: 52, label: 'Moderate', priority: 'medium', impact: 'Supply chain optimization', insights: ['Inventory issues causing stockouts', 'Manual order fulfillment creating delays'] },
      marketing: { score: 71, label: 'Opportunity', priority: 'medium', impact: '4x organic traffic potential', insights: ['Excellent social presence but SEO is weak', 'Blog content drives less than 5% of traffic', 'Email list of 45K subscribers under-monetized'] },
      outsourcing: { score: 68, label: 'Recommended', priority: 'medium', impact: 'Accelerate development 3x', insights: ['Founder is doing all technical work alone', 'Needs dedicated development team to scale', '3 months backlog of feature requests'] },
    },
    contacts: [
      { name: 'Emma Walsh', role: 'Founder & CEO', linkedin: 'linkedin.com/in/emmawalsh-greenleaf', email: 'emma@greenleaforganics.co' },
      { name: 'Tyler Brooks', role: 'Head of Marketing', linkedin: 'linkedin.com/in/tylerbrooks' },
    ],
    social: {
      instagram: 'instagram.com/greenleaforganics',
      twitter: 'twitter.com/greenleaff',
      linkedin: 'linkedin.com/company/greenleaf-organics',
    },
    techStack: ['Shopify', 'Klaviyo', 'Meta Ads', 'Yotpo'],
    intentSignals: [
      { type: 'funding', description: 'Raised $3.2M seed round, planning platform rebuild', date: '2026-05-25', strength: 'strong' },
      { type: 'hiring', description: 'Looking for Head of Technology', date: '2026-05-18', strength: 'strong' },
    ],
    lastActivity: '1 day ago',
    addedDate: '2026-05-31',
  },
  {
    id: 'lead-004',
    company: 'PrimeFreight Logistics',
    website: 'primefreight.net',
    industry: 'Logistics',
    sector: 'Freight & Transportation',
    location: 'Dallas, TX',
    country: 'United States',
    countryCode: 'US',
    employees: '200-500',
    revenue: '$35M - $60M',
    founded: '2012',
    description: 'Regional freight and logistics company serving mid-size manufacturers across the US Southwest.',
    score: 76,
    scoreCategory: 'warm',
    websiteScore: 28,
    seoScore: 22,
    mobileScore: 31,
    performanceScore: 35,
    securityScore: 48,
    aiInsight: 'PrimeFreight is running operations on a 12-year-old legacy system with no customer portal, no real-time tracking, and no mobile capabilities. Their largest customer recently complained publicly about visibility issues. Industry disruption from Amazon Logistics and Flexport means PrimeFreight must modernize fast or risk losing market share.',
    opportunities: {
      website: { score: 93, label: 'Critical', priority: 'high', impact: 'Customer retention — $2.8M ARR at risk', insights: ['Website from 2012 — cannot compete with modern competitors', 'No online quote tool (requires phone call)', 'Zero customer portal for shipment tracking', 'Largest competitor just launched real-time tracking'] },
      mobile: { score: 88, label: 'High Priority', priority: 'high', impact: 'Operational efficiency + customer satisfaction', insights: ['Drivers using paper-based documentation', 'No mobile dispatch or route optimization', 'Customers request mobile tracking daily per support tickets'] },
      erp: { score: 91, label: 'Critical', priority: 'high', impact: '$1.2M operational cost reduction', insights: ['Legacy TMS system from 2011 — no API access', '12+ manual processes that could be automated', 'Finance team spending 3 days/month on manual reconciliation', 'Route optimization done via spreadsheets'] },
      marketing: { score: 58, label: 'Moderate', priority: 'medium', impact: 'New customer acquisition', insights: ['Almost zero online visibility', 'Competitors dominating local SEO', 'No digital marketing presence whatsoever'] },
      outsourcing: { score: 82, label: 'High Priority', priority: 'high', impact: 'Rapid modernization at fraction of hiring cost', insights: ['No in-house development team', 'IT budget allocated for modernization per annual report', 'CTO role vacant for 8 months'] },
    },
    contacts: [
      { name: 'Robert Martinez', role: 'CEO', email: 'r.martinez@primefreight.net' },
      { name: 'Lisa Thompson', role: 'VP Operations', linkedin: 'linkedin.com/in/lisathompsonops' },
    ],
    social: { linkedin: 'linkedin.com/company/primefreight' },
    techStack: ['Legacy TMS', 'QuickBooks', 'Excel'],
    intentSignals: [
      { type: 'tech-change', description: 'CTO posting about digital transformation roadmap', date: '2026-05-22', strength: 'strong' },
      { type: 'expansion', description: 'Won 3 new enterprise contracts requiring platform upgrade', date: '2026-05-08', strength: 'medium' },
    ],
    lastActivity: '6 days ago',
    addedDate: '2026-05-26',
  },
  {
    id: 'lead-005',
    company: 'Meridian Healthcare Group',
    website: 'meridianhg.com',
    industry: 'Healthcare',
    sector: 'Medical Services',
    location: 'Chicago, IL',
    country: 'United States',
    countryCode: 'US',
    employees: '1000-2000',
    revenue: '$120M - $180M',
    founded: '2005',
    description: 'Multi-specialty healthcare network with 18 clinics across Illinois and Indiana.',
    score: 85,
    scoreCategory: 'hot',
    websiteScore: 48,
    seoScore: 55,
    mobileScore: 43,
    performanceScore: 61,
    securityScore: 74,
    aiInsight: 'Meridian Healthcare is hemorrhaging potential patients to competitors with better digital experiences. Their online appointment booking has a 68% abandonment rate. In healthcare, a 1% improvement in online patient acquisition translates to approximately $600K in additional annual revenue at their scale.',
    opportunities: {
      website: { score: 88, label: 'High Priority', priority: 'high', impact: '$1.8M annual patient acquisition uplift', insights: ['Appointment booking abandonment at 68%', 'Mobile experience rated 2.1/5 by patients', 'HIPAA-compliant patient portal is needed', '40% of appointment calls could be digital'] },
      mobile: { score: 84, label: 'High Priority', priority: 'high', impact: 'Patient engagement and retention', insights: ['Telemedicine demand grew 340% post-COVID', 'Competitors have mobile patient apps', 'Prescription reminders and appointment scheduling via app would reduce no-shows'] },
      erp: { score: 76, label: 'Opportunity', priority: 'medium', impact: '$640K annual efficiency gain', insights: ['Billing and clinical systems not integrated', 'Staff manually reconciling insurance claims', '4 different EMR systems across clinics'] },
      marketing: { score: 69, label: 'Opportunity', priority: 'medium', impact: 'Patient acquisition from digital channels', insights: ['Google local rankings behind competitors', 'Patient review management is weak', 'Content marketing untapped'] },
      outsourcing: { score: 55, label: 'Moderate', priority: 'medium', impact: 'Healthcare IT talent', insights: ['Specialized healthcare software development needed', 'HIPAA compliance expertise required', 'In-house team lacks healthcare app experience'] },
    },
    contacts: [
      { name: 'Dr. Patricia Cole', role: 'CEO', linkedin: 'linkedin.com/in/drcole-meridian' },
      { name: 'Kevin Zhang', role: 'Chief Information Officer', email: 'k.zhang@meridianhg.com' },
      { name: 'Rachel Adams', role: 'VP Digital Experience', linkedin: 'linkedin.com/in/racheladams' },
    ],
    social: {
      linkedin: 'linkedin.com/company/meridian-healthcare',
      facebook: 'facebook.com/meridianhealthcare',
    },
    techStack: ['Epic EMR', 'Microsoft Azure', 'Salesforce Health Cloud'],
    intentSignals: [
      { type: 'hiring', description: 'Hiring Director of Digital Transformation', date: '2026-05-26', strength: 'strong' },
      { type: 'expansion', description: '3 new clinic locations opening Q4 2026', date: '2026-05-15', strength: 'medium' },
    ],
    lastActivity: '3 days ago',
    addedDate: '2026-05-29',
  },
  {
    id: 'lead-006',
    company: 'Atlas Wealth Management',
    website: 'atlaswm.com',
    industry: 'Finance',
    sector: 'Wealth Management',
    location: 'New York, NY',
    country: 'United States',
    countryCode: 'US',
    employees: '100-250',
    revenue: '$50M - $90M',
    founded: '2014',
    description: 'Independent RIA managing $2.8B in AUM for high-net-worth individuals and family offices.',
    score: 71,
    scoreCategory: 'warm',
    websiteScore: 45,
    seoScore: 38,
    mobileScore: 52,
    performanceScore: 58,
    securityScore: 81,
    aiInsight: 'Atlas Wealth Management serves ultra-high-net-worth clients but their digital presence does not reflect their premium positioning. Their website looks generic compared to Goldman Sachs Private Wealth and JPMorgan Private Bank. In wealth management, a premium digital presence directly correlates with AUM growth.',
    opportunities: {
      website: { score: 82, label: 'High Priority', priority: 'high', impact: 'AUM growth through digital trust signals', insights: ['Website design is generic — does not reflect $2.8B AUM scale', 'Client portal login is a third-party widget — security perception issue', 'No investment philosophy or thought leadership content', 'Competitor Baird Private Wealth has significantly superior digital presence'] },
      mobile: { score: 74, label: 'Opportunity', priority: 'medium', impact: 'Client engagement and retention', insights: ['HNWI clients expect mobile portfolio access', 'No dedicated client relationship app', 'Portfolio performance viewing requires desktop'] },
      erp: { score: 58, label: 'Moderate', priority: 'medium', impact: 'Advisor productivity gains', insights: ['CRM and financial planning tools disconnected', 'Advisor onboarding process is manual and slow'] },
      marketing: { score: 71, label: 'Opportunity', priority: 'medium', impact: 'New HNW client acquisition', insights: ['Almost zero content marketing', 'LinkedIn presence is weak for an AUM-stage firm', 'Referral program could be systematized digitally'] },
      outsourcing: { score: 42, label: 'Low Priority', priority: 'low', impact: 'Specialized fintech development', insights: ['Would benefit from fintech-specialized developers', 'SEC compliance requirements need careful handling'] },
    },
    contacts: [
      { name: 'Andrew Blackwell', role: 'Managing Partner', linkedin: 'linkedin.com/in/andrewblackwell' },
      { name: 'Nina Patel', role: 'Head of Client Experience', email: 'n.patel@atlaswm.com' },
    ],
    social: {
      linkedin: 'linkedin.com/company/atlas-wealth-management',
      twitter: 'twitter.com/atlaswm',
    },
    techStack: ['Salesforce', 'Orion Advisor', 'Black Diamond', 'DocuSign'],
    intentSignals: [
      { type: 'launch', description: 'Launching new ESG investment platform in Q3', date: '2026-05-24', strength: 'medium' },
    ],
    lastActivity: '5 days ago',
    addedDate: '2026-05-27',
  },
  {
    id: 'lead-007',
    company: 'SwiftBuild Construction',
    website: 'swiftbuildcorp.com',
    industry: 'Construction',
    sector: 'Commercial Construction',
    location: 'Phoenix, AZ',
    country: 'United States',
    countryCode: 'US',
    employees: '500-1000',
    revenue: '$80M - $130M',
    founded: '2008',
    description: 'Commercial general contractor specializing in industrial and mixed-use developments across the Southwest.',
    score: 66,
    scoreCategory: 'warm',
    websiteScore: 31,
    seoScore: 29,
    mobileScore: 28,
    performanceScore: 34,
    securityScore: 44,
    aiInsight: 'SwiftBuild is winning large contracts but their operational inefficiency is costing them an estimated $4.2M annually in rework, delays, and miscommunication. An ERP system combined with a project client portal would be transformative. The construction industry is rapidly digitizing and laggards risk losing bids to digitally-enabled competitors.',
    opportunities: {
      website: { score: 84, label: 'High Priority', priority: 'high', impact: 'Contract win rate improvement', insights: ['Website looks like a 2010 brochure site', 'No project portfolio showcase with rich media', 'Cannot submit project inquiries online', 'Competitors Turner and Skanska have exceptional digital presence'] },
      mobile: { score: 76, label: 'Opportunity', priority: 'medium', impact: 'Field productivity improvement', insights: ['Field crews using paper forms and phone calls', 'No mobile app for site documentation', 'Safety incident reporting is manual'] },
      erp: { score: 94, label: 'Critical', priority: 'high', impact: '$4.2M annual efficiency gain', insights: ['Project management done via spreadsheets and email', 'Budget overruns averaging 12% per project', 'Subcontractor management is completely manual', 'Document version control is a major issue', 'No integrated bid management system'] },
      marketing: { score: 62, label: 'Moderate', priority: 'medium', impact: 'New contract pipeline growth', insights: ['Zero digital marketing investment', 'Trade associations and word-of-mouth only', 'LinkedIn company page has only 45 followers'] },
      outsourcing: { score: 71, label: 'Opportunity', priority: 'medium', impact: 'Technology acceleration', insights: ['No internal tech team', 'Recently lost IT contract manager', 'Budget set aside for construction tech per CFO LinkedIn post'] },
    },
    contacts: [
      { name: 'Greg Hamilton', role: 'CEO & Founder', linkedin: 'linkedin.com/in/greghamilton-construction' },
      { name: 'Maria Santos', role: 'VP Operations', email: 'm.santos@swiftbuildcorp.com' },
    ],
    social: { linkedin: 'linkedin.com/company/swiftbuild-construction' },
    techStack: ['Procore (partial)', 'QuickBooks', 'Excel', 'AutoCAD'],
    intentSignals: [
      { type: 'tech-change', description: 'Posted about moving away from Excel for project management', date: '2026-05-19', strength: 'strong' },
      { type: 'hiring', description: 'Hiring Project Manager and IT Coordinator', date: '2026-05-14', strength: 'medium' },
    ],
    lastActivity: '1 week ago',
    addedDate: '2026-05-25',
  },
  {
    id: 'lead-008',
    company: 'Luminary EdTech',
    website: 'luminarylearn.io',
    industry: 'Education',
    sector: 'Online Learning',
    location: 'Toronto, Canada',
    country: 'Canada',
    countryCode: 'CA',
    employees: '100-200',
    revenue: '$12M - $20M',
    founded: '2021',
    description: 'AI-powered professional skills development platform targeting enterprise L&D departments.',
    score: 89,
    scoreCategory: 'hot',
    websiteScore: 62,
    seoScore: 58,
    mobileScore: 54,
    performanceScore: 67,
    securityScore: 78,
    aiInsight: 'Luminary has strong product-market fit but their mobile experience is holding back growth. 72% of learners attempt content on mobile but completion rates are 43% lower than desktop. A dedicated learning mobile app with offline content, gamification, and push notification reminders could unlock their B2C expansion.',
    fundingStage: 'Series A',
    fundingAmount: '$12M',
    opportunities: {
      website: { score: 68, label: 'Improvement', priority: 'medium', impact: 'Demo request conversion improvement', insights: ['Enterprise demo conversion rate is 2.1% — should be 4%+', 'Product showcase is static, needs interactive demo', 'Case study section is weak — no quantified results'] },
      mobile: { score: 93, label: 'Critical', priority: 'high', impact: '60% learning completion improvement', insights: ['Mobile learner completion 43% lower than desktop', 'No dedicated iOS/Android app', 'Competitors Coursera and LinkedIn Learning have superior mobile', 'Push notification capability would directly impact retention KPIs'] },
      erp: { score: 44, label: 'Low', priority: 'low', impact: 'Operational efficiency', insights: ['Team is relatively lean and efficient', 'Could benefit from unified HR and project management'] },
      marketing: { score: 77, label: 'High Priority', priority: 'high', impact: '5x organic growth potential', insights: ['EdTech SEO is highly competitive but Luminary has unique AI angle', 'Content marketing budget exists but strategy is weak', 'Thought leadership could differentiate significantly'] },
      outsourcing: { score: 81, label: 'High Priority', priority: 'high', impact: '3x feature delivery speed', insights: ['Engineering team of 8 is bottleneck for roadmap', 'Mobile development expertise gap is clear', 'Augmenting with 3-4 specialist developers would transform delivery'] },
    },
    contacts: [
      { name: 'Priya Sharma', role: 'Co-Founder & CEO', linkedin: 'linkedin.com/in/priyasharma-luminary', email: 'priya@luminarylearn.io' },
      { name: 'Alex Johansson', role: 'CPO', linkedin: 'linkedin.com/in/alexjohansson' },
      { name: 'Sam Kim', role: 'Head of Enterprise Sales', email: 's.kim@luminarylearn.io' },
    ],
    social: {
      linkedin: 'linkedin.com/company/luminary-edtech',
      twitter: 'twitter.com/luminarylearn',
    },
    techStack: ['React', 'Python', 'AWS', 'Stripe', 'Amplitude', 'Intercom'],
    intentSignals: [
      { type: 'funding', description: 'Closed $12M Series A to accelerate product development', date: '2026-05-22', strength: 'strong' },
      { type: 'hiring', description: '8 open roles including Mobile Engineers', date: '2026-05-20', strength: 'strong' },
      { type: 'expansion', description: 'Expanding to US enterprise market Q3', date: '2026-05-16', strength: 'medium' },
    ],
    lastActivity: '2 days ago',
    addedDate: '2026-05-30',
  },
]

export const WEEKLY_CHART_DATA = [
  { day: 'Mon', leads: 18, opportunities: 52, outreach: 34 },
  { day: 'Tue', leads: 24, opportunities: 71, outreach: 48 },
  { day: 'Wed', leads: 31, opportunities: 89, outreach: 62 },
  { day: 'Thu', leads: 22, opportunities: 64, outreach: 41 },
  { day: 'Fri', leads: 28, opportunities: 95, outreach: 73 },
  { day: 'Sat', leads: 12, opportunities: 38, outreach: 21 },
  { day: 'Sun', leads: 9, opportunities: 28, outreach: 15 },
]

export const MONTHLY_CHART_DATA = [
  { month: 'Jan', leads: 342, value: 820 },
  { month: 'Feb', leads: 418, value: 940 },
  { month: 'Mar', leads: 489, value: 1120 },
  { month: 'Apr', leads: 521, value: 1340 },
  { month: 'May', leads: 612, value: 1580 },
  { month: 'Jun', leads: 487, value: 1200 },
]

export const INDUSTRY_DATA = [
  { name: 'Technology', value: 28, color: '#007BFF' },
  { name: 'Healthcare', value: 18, color: '#00D4FF' },
  { name: 'E-Commerce', value: 15, color: '#6C63FF' },
  { name: 'Finance', value: 12, color: '#FF6B9D' },
  { name: 'Logistics', value: 10, color: '#00D4A1' },
  { name: 'Other', value: 17, color: '#4a6580' },
]

export const OUTREACH_TEMPLATES: OutreachTemplate[] = [
  {
    id: 'tmpl-001',
    name: 'Website Opportunity Email',
    type: 'email',
    subject: 'Quick observation about {{company}}.com',
    body: `Hi {{firstName}},

I was researching {{industry}} companies in {{location}} and came across {{company}}.

I noticed a few opportunities on your website that could significantly impact your growth — particularly around mobile performance and conversion optimization. Your current page load time is around {{loadTime}}, which is likely costing you meaningful revenue.

At Fixels Media, we help companies like {{company}} transform their digital presence and typically see a 40-60% improvement in conversion rates within the first 90 days.

Would you be open to a 20-minute discovery call this week? I'd love to share some specific data we've found about {{company}}'s digital opportunity.

Best,
[Your Name]
Fixels Media`,
    tags: ['website', 'cold-outreach', 'conversion'],
  },
  {
    id: 'tmpl-002',
    name: 'LinkedIn Connection Request',
    type: 'linkedin',
    body: `Hi {{firstName}}, I've been following {{company}}'s growth in the {{industry}} space — impressive work. I have some insights about digital opportunities specific to your business that I think you'd find valuable. Would love to connect.`,
    tags: ['linkedin', 'connection', 'cold'],
  },
  {
    id: 'tmpl-003',
    name: 'Mobile App Opportunity',
    type: 'email',
    subject: 'Why {{company}} needs a mobile app in 2026',
    body: `Hi {{firstName}},

{{company}} has impressive {{metric}} — but I noticed you don't have a dedicated mobile app yet, despite {{mobileTrafficPercent}}% of your traffic coming from mobile devices.

Your top 3 competitors ({{competitor1}}, {{competitor2}}, {{competitor3}}) all have native apps, and studies show mobile app users have 3x higher lifetime value.

Fixels Media has built 50+ mobile apps in the {{industry}} space. We could have an MVP live within 60 days.

Can we schedule a quick demo to show you what this could look like for {{company}}?

[Your Name]`,
    tags: ['mobile', 'app', 'opportunity'],
  },
  {
    id: 'tmpl-004',
    name: 'Post-Funding Congratulations',
    type: 'email',
    subject: 'Congratulations on the {{fundingAmount}} raise, {{firstName}}',
    body: `Hi {{firstName}},

Congratulations on {{company}}'s {{fundingAmount}} {{fundingRound}} — well deserved given the traction you've built.

Many founders in your position use this milestone to invest in the digital infrastructure needed to scale. At Fixels Media, we've helped several {{fundingRound}}-stage companies rapidly build the technical foundation that supports their next phase of growth.

Given your growth trajectory, now is the perfect time to discuss how we can accelerate your digital roadmap.

Would you have 20 minutes this week?

Best,
[Your Name]
Fixels Media`,
    tags: ['funding', 'congratulations', 'warm'],
  },
]
